version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      # змінні оточення я б виніс у .env файл та описав у .env.sample

    

  flask:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8000:5000

    # command: python3 app.py
    
    volumes:
      - .:/app