version: "3"


services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:80
    networks:
      - app
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    environment:
      PYTHONBUFFERED: 1
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app



  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursor_dbx
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - app


networks:
  app:
    driver: bridge