version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
      MYSQL_DATABASE: flask
    ports:
      - 3310:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - app


  app:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
      - app
    volumes:
      - .:/app


  nginx:
    image: nginx:1.23-alpine
    ports:
      - 1440:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - app

networks:
  app:
    driver: bridge