# Generated by Django 4.2.1 on 2023-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='rJuMQXBQiNvyPESp', max_length=32)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('discount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
