# Generated by Django 4.2.1 on 2023-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='slug', max_length=255, unique=True),
        ),
    ]
